version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: emsdb
      POSTGRES_USER: emsuser
      POSTGRES_PASSWORD: 00000000
    ports:
      - "5434:5432"

  app:
    image: ems-task:latest
    depends_on:
      - db
    environment:
      DB_URL2: jdbc:postgresql://db:5432/emsdb
      DB_USERNAME2: emsuser
      DB_PASSWORD2: 00000000
      USER_URL: http://192.168.118.82:8080/api/v1

    ports:
      - "8081:8080"
